# **Homework 1 : Intro to Machine Learning**

In [1]:
import pandas as pd

pd.__version__

'2.3.1'

In [2]:
import requests, urllib
from tqdm import tqdm

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
resp = requests.get(url)
laptops_data = resp.content

In [3]:
csv_file = open('laptops.csv', 'wb')
csv_file.write(laptops_data)

298573

In [4]:
df = pd.read_csv('laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [5]:
df.shape

(2160, 12)

In [6]:
len(df.Brand.unique())

27

In [7]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [8]:
df[(df['Brand'] == 'Dell')]['Final Price'].max()

np.float64(3936.0)

In [9]:
print(f"The original median value of Screen column: {df.Screen.median()}")

screen_mode = df.Screen.mode()
df.Screen = df.Screen.fillna(screen_mode)

print(f"The current median value of Screen column: {df.Screen.median()}")

The original median value of Screen column: 15.6
The current median value of Screen column: 15.6


In [ ]:
InnjooDf = df.loc[df.Brand == 'Innjoo'][['RAM', 'Storage', 'Screen']]
InnjooDf

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [31]:
import numpy as np
X = InnjooDf.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [32]:
X_T = X.T
X_T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [33]:
XTX = X_T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [34]:
XTX_invs = np.linalg.inv(XTX)
XTX_invs

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [38]:
XTX_invs.dot(XTX)

array([[ 1.00000000e+00, -2.75571802e-13,  6.32385368e-15],
       [ 1.02488553e-16,  1.00000000e+00,  8.14222656e-17],
       [-7.04660473e-16, -2.84062325e-14,  1.00000000e+00]])

In [39]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [40]:
w = XTX_invs.dot(X_T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [41]:
w.sum()

np.float64(91.2998806299555)